# -*- coding: utf-8 -*-
"""Untitled1.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1mOhJK4Dm3Dq64QdXUVLLvoOUXqnCSVrO
"""

import random
import datetime

print("=" * 60)
print("        🤖 AI CHATBOT DEVELOPMENT PROJECT 🤖")
print("=" * 60)
print("Hello! I am your AI Chatbot.")
print("Type 'help' to see available commands.")
print("Type 'bye' to exit.")
print("=" * 60)

greetings = [
    "Hello! Nice to meet you.",
    "Hi! How can I help you today?",
    "Welcome! Ask me anything."
]

jokes = [
    "Why do programmers prefer dark mode? Because light attracts bugs!",
    "Why did the computer go to the doctor? It had a virus!",
    "Why was the computer cold? It forgot to close Windows!"
]

quotes = [
    "Success comes to those who never stop learning.",
    "Practice makes progress.",
    "Believe in yourself and keep improving every day."
]

while True:

    user = input("\nYou : ").lower().strip()

    if user == "bye":
        print("Bot : Goodbye! Have a wonderful day.")
        break

    elif user == "help":
        print("\nAvailable Commands")
        print("------------------------------")
        print("hello")
        print("hi")
        print("how are you")
        print("your name")
        print("time")
        print("date")
        print("joke")
        print("quote")
        print("python")
        print("ai")
        print("college")
        print("thank you")
        print("bye")

    elif "hello" in user or "hi" in user:
        print("Bot :", random.choice(greetings))

    elif "how are you" in user:
        print("Bot : I am doing great! Thank you for asking.")

    elif "your name" in user or "who are you" in user:
        print("Bot : I am an AI Chatbot created using Python.")

    elif "time" in user:
        current_time = datetime.datetime.now().strftime("%I:%M:%S %p")
        print("Bot : Current Time is", current_time)

    elif "date" in user:
        current_date = datetime.datetime.now().strftime("%d-%m-%Y")
        print("Bot : Today's Date is", current_date)

    elif "joke" in user:
        print("Bot :", random.choice(jokes))

    elif "quote" in user:
        print("Bot :", random.choice(quotes))

    elif "python" in user:
        print("Bot : Python is a powerful programming language used in AI, Web Development, Data Science and Automation.")

    elif "ai" in user or "artificial intelligence" in user:
        print("Bot : Artificial Intelligence enables machines to learn, reason and solve problems like humans.")

    elif "college" in user:
        print("Bot : I hope your studies are going well. Keep practicing programming every day!")

    elif "thank" in user:
        print("Bot : You're welcome! Happy to help.")

    elif "weather" in user:
        city = input("Bot : Which city? ")
        print(f"Bot : Sorry, I cannot check live weather for {city} without internet access.")

    elif "age" in user:
        print("Bot : I don't have an age. I was created using Python.")

    elif "favorite color" in user:
        print("Bot : I like blue because it reminds me of technology.")

    elif "good morning" in user:
        print("Bot : Good Morning! Have a productive day!")

    elif "good night" in user:
        print("Bot : Good Night! Sleep well.")

    elif "bye bye" in user:
        print("Bot : See you again!")
        break

    else:
        print("Bot : Sorry, I don't understand that.")
        print("Type 'help' to see available commands.")